import os
import feedparser
import google.genai as genai
import resend

# Get api keys
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
MY_EMAIL = os.getenv("MY_EMAIL")

# Setup the api keys
client = genai.Client(api_key=GEMINI_API_KEY)
resend.api_key = RESEND_API_KEY

# List of RSS feeds (add the ones you like)
RSS_FEEDS = [
    "https://techcrunch.com/feed/",
    "https://www.theverge.com/rss/index.xml"
]

# Topics you want to hear about
MY_INTERESTS = """
I am interested in:
- AI agents and automation
- New LLM models and AI updates
- Interesting open-source projects and robotics
IGNORE: News about large corporate business deals, corporate gossip, and generic product reviews.
"""

def search_essays():
    essays = []
    for feed_url in RSS_FEEDS:
        feed = feedparser.parse(feed_url)
        for entry in feed.entries[:5]:  # Get the 5 most recent
            essays.append({
                "titulo": entry.title,
                "link": entry.link,
                "resumo": entry.get("summary", "")
            })
    return essays

def analize_with_gemini(essays):
    prompt = f"""
    You are a strict, direct personal content curator.
    
    Interest profile:
    {MY_INTERESTS}
    
    Articles from this week:
    {essays}
    
    Instructions:
    1. Analyze the title and summary of each article.
    2. Select ONLY the articles that genuinely match the profile.
    3. Create a clean, modern HTML email that is easy to read on mobile devices.
    4. DO NOT include markdown fences such as ```html or ``` at the beginning or end. Return ONLY pure HTML code.
    
    Use this exact structure and inline CSS for each selected article:

    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9fafb;">
        <h1 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; font-size: 22px;">📰 Weekly News Briefing</h1>
        
        <!-- REPEAT THIS BLOCK FOR EACH RELEVANT ARTICLE -->
        <div style="background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <h2 style="margin-top: 0; color: #1f2937; font-size: 18px; line-height: 1.4;">[ARTICLE TITLE]</h2>
            <p style="color: #4b5563; font-size: 14px; line-height: 1.6;">[A 2-SENTENCE SUMMARY EXPLAINING THE CONTENT AND WHY IT IS RELEVANT]</p>
            <a href="[ARTICLE_LINK]" style="display: inline-block; background-color: #2563eb; color: #ffffff; text-decoration: none; padding: 8px 14px; border-radius: 6px; font-weight: bold; font-size: 13px;">Read full article &rarr;</a>
        </div>
        <!-- END OF BLOCK -->

        <!-- IF NO ARTICLE IS RELEVANT, RETURN ONLY ONE MESSAGE INSIDE A CARD SAYING THE WEEK WAS QUIET -->
        
        <p style="text-align: center; color: #9ca3af; font-size: 12px; margin-top: 30px;">Automatically generated by your AI agent.</p>
    </div>
    """
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt
    )
    return response.text

def send_email(html_content):
    params = {
        "from": "News Agent <onboarding@resend.dev>",
        "to": [MY_EMAIL],
        "subject": "📰 Weekly News Briefing",
        "html": html_content,
    }
    resend.Emails.send(params)

if __name__ == "__main__":
    print("Getting RSS...")
    essays = search_essays()
    print("Filtering with Gemini...")
    report = analize_with_gemini(essays)
    print("Sending...")
    send_email(report)
    print("Done!")
