name: Run new agent

on:
  schedule:
    #Monday 7AM Brasília
    - cron: '0 10 * * 1' 
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependecies
        run: |
          pip install -r requirements.txt
          
      - name: Run agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
        run: python agent.py
